FROM python:3.11-slim-bookworm

WORKDIR /usr/src

RUN pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install flask

COPY app/ /usr/src/app

EXPOSE 5000

CMD [ "python", "/usr/src/app/app.py" ]