FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get upgrade -y

# change working directory
WORKDIR /usr/src


# install torch cpu 
RUN pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu && pip install flask

COPY app/ /usr/src/app

EXPOSE 5000

CMD [ "python", "/usr/src/app/app.py" ]